# Generated by Django 5.1.5 on 2025-02-04 14:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordlist', '0002_titlemodel_content_titlemodel_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titlemodel',
            name='content',
        ),
        migrations.RemoveField(
            model_name='titlemodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='titlemodel',
            name='page_number',
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordlist.titlemodel')),
            ],
        ),
    ]
